services:
  app:
    platform: linux/amd64
    volumes:
      - .:/var/www/html

  queue-1:
    platform: linux/amd64
    volumes:
      - .:/var/www/html

  queue-2:
    platform: linux/amd64
    volumes:
      - .:/var/www/html
