#remove volumes for production only good for local #development, so mounted files in the container
#reflect changes.

services:
    app:
        build: .
        container_name: migration-app
        restart: unless-stopped
        env_file:
            - .env
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${MYSQL_DATABASE}
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - migration
    #queue worker, for AI llm file upload validation
    #better performance, parallel jobs.
    queue-1:
        build: .
        container_name: migration-worker-1
        restart: unless-stopped
        command: php artisan queue:work --sleep=3 --tries=3
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${MYSQL_DATABASE}
        networks:
            - migration
    queue-2:
        build: .
        container_name: migration-worker-2
        restart: unless-stopped
        command: php artisan queue:work --sleep=3 --tries=3
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${MYSQL_DATABASE}
        networks:
            - migration

    mysql:
        image: mysql:8.4
        ports:
            - "3306:3306"
        container_name: migration-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - migration-db:/var/lib/mysql
        networks:
            - migration


    ollama:
        image: ollama/ollama:latest
        container_name: migration-ollama
        restart: unless-stopped
        ports:
            - "11434:11434"
        volumes:
            - ollama-data:/root/.ollama
        networks:
            - migration


    web:
        build:
            context: .
            target: web
        container_name: migration-caddy
        restart: unless-stopped
        ports:
            - "8080:80"
        networks:
            - migration
            - caddy_net



networks:
    migration:

    caddy_net:
        external: true
volumes:
    migration-db:
    ollama-data:


